### ISSUE TITLE
LICENSE is missing

### ISSUE THREAD

**Issue by beniza** [abid-mujtaba/ttf-jameel-noori-nastaleeq#1]
I'd like to use Jameel Noori font in an upcoming project. Could you please specify the license under which you're releasing this font?

**Comment by abid-mujtaba** [comment]
Hi. This font has been bouncing around the internet for a few years. The last time I found it was on Urdu Jahan. When that disappeared it I uploaded my copy here. I don't claim authorship or ownership of it so I am unclear whether I should attach a license to it.

**Comment by beniza** [comment]
Okay I understand. So I'll refrain from making any modifications to it. Thanks.
